#!/usr/bin/env bash
# Deploy MarketFactory and Treasury to Stellar Testnet.
# Requirements: Rust + wasm32 target, Stellar CLI (soroban), funded Testnet keypair.
#
# Usage:
#   ADMIN_SECRET=S... ./deploy_testnet.sh
#
# Outputs contract IDs to stdout and saves them to .env.testnet in this directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.testnet"

# ─── VALIDATE ENVIRONMENT ─────────────────────────────────────────────────────

if [[ -z "${ADMIN_SECRET:-}" ]]; then
  echo "ERROR: ADMIN_SECRET is not set. Export your Testnet secret key first."
  echo "  export ADMIN_SECRET=SABC..."
  exit 1
fi

for cmd in cargo soroban; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is not installed or not in PATH."
    exit 1
  fi
done

NETWORK="testnet"
NETWORK_URL="https://soroban-testnet.stellar.org"
ADMIN_PUBKEY=$(stellar keys address "$ADMIN_SECRET" 2>/dev/null || \
               soroban keys address "$ADMIN_SECRET" 2>/dev/null || \
               echo "")

if [[ -z "$ADMIN_PUBKEY" ]]; then
  echo "ERROR: Could not derive public key from ADMIN_SECRET."
  exit 1
fi

echo "==> Admin public key: $ADMIN_PUBKEY"

# ─── BUILD ────────────────────────────────────────────────────────────────────

echo ""
echo "==> Building contracts (release, wasm32-unknown-unknown)..."
cd "$CONTRACTS_DIR"
cargo build --release --target wasm32-unknown-unknown 2>&1

WASM_DIR="$CONTRACTS_DIR/target/wasm32-unknown-unknown/release"

# ─── OPTIMIZE ─────────────────────────────────────────────────────────────────

echo ""
echo "==> Optimizing WASM binaries..."
for contract in treasury market_factory; do
  WASM_IN="$WASM_DIR/${contract}.wasm"
  WASM_OUT="$WASM_DIR/${contract}.optimized.wasm"

  if [[ ! -f "$WASM_IN" ]]; then
    echo "ERROR: $WASM_IN not found after build."
    exit 1
  fi

  soroban contract optimize \
    --wasm       "$WASM_IN" \
    --wasm-out   "$WASM_OUT"
  echo "    Optimized: $WASM_OUT"
done

# ─── DEPLOY TREASURY ──────────────────────────────────────────────────────────

echo ""
echo "==> Deploying Treasury..."
TREASURY_ID=$(soroban contract deploy \
  --wasm       "$WASM_DIR/treasury.optimized.wasm" \
  --source     "$ADMIN_SECRET" \
  --network    "$NETWORK" \
  --network-passphrase "Test SDF Network ; September 2015" \
  --rpc-url    "$NETWORK_URL")

echo "    Treasury contract ID: $TREASURY_ID"

echo ""
echo "==> Initializing Treasury..."
soroban contract invoke \
  --id         "$TREASURY_ID" \
  --source     "$ADMIN_SECRET" \
  --network    "$NETWORK" \
  --network-passphrase "Test SDF Network ; September 2015" \
  --rpc-url    "$NETWORK_URL" \
  -- initialize \
  --admin      "$ADMIN_PUBKEY" \
  --factory    "PLACEHOLDER_FACTORY_ID"

# ─── DEPLOY MARKET FACTORY ────────────────────────────────────────────────────

echo ""
echo "==> Deploying MarketFactory..."
FACTORY_ID=$(soroban contract deploy \
  --wasm       "$WASM_DIR/market_factory.optimized.wasm" \
  --source     "$ADMIN_SECRET" \
  --network    "$NETWORK" \
  --network-passphrase "Test SDF Network ; September 2015" \
  --rpc-url    "$NETWORK_URL")

echo "    MarketFactory contract ID: $FACTORY_ID"

echo ""
echo "==> Initializing MarketFactory..."
soroban contract invoke \
  --id         "$FACTORY_ID" \
  --source     "$ADMIN_SECRET" \
  --network    "$NETWORK" \
  --network-passphrase "Test SDF Network ; September 2015" \
  --rpc-url    "$NETWORK_URL" \
  -- initialize \
  --admin         "$ADMIN_PUBKEY" \
  --fee-collector "$TREASURY_ID" \
  --default-fee-bp 200 \
  --min-bet       1000000 \
  --max-bet       100000000000

# ─── RE-INITIALIZE TREASURY WITH REAL FACTORY ─────────────────────────────────
# Treasury initialize is idempotent-guard so we cannot call it twice.
# If you need to update the factory reference post-deploy, upgrade the contract
# or add an update_factory admin function before production deployment.

# ─── SAVE OUTPUT ──────────────────────────────────────────────────────────────

echo ""
echo "==> Saving contract IDs to $ENV_FILE..."
cat > "$ENV_FILE" <<ENVFILE
# BOXMEOUT Stellar Testnet — generated by deploy_testnet.sh
NETWORK=testnet
RPC_URL=${NETWORK_URL}
ADMIN_PUBKEY=${ADMIN_PUBKEY}
TREASURY_CONTRACT_ID=${TREASURY_ID}
FACTORY_CONTRACT_ID=${FACTORY_ID}
ENVFILE

echo ""
echo "======================================================"
echo "  TREASURY_CONTRACT_ID = $TREASURY_ID"
echo "  FACTORY_CONTRACT_ID  = $FACTORY_ID"
echo "======================================================"
echo ""
echo "Contract IDs saved to: $ENV_FILE"
echo "Add contracts/scripts/.env.testnet to .gitignore if not already done."
